name: Build a Docker image and Push it to ACR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: finderwiredev.azurecr.io
        username: finderwiredev
        password: yW9LL03jqtW4BgIexeXnLQJXskDfyzZP/Pp04QQ3sf+ACRBb5non
    - run: |
        docker build . -t finderwiredev.azurecr.io/springboot-liquibase-demo:${{ github.sha }}
        docker push finderwiredev.azurecr.io/springboot-liquibase-demo:${{ github.sha }}
